services:
  web:
    build:
      context: ../apps/web
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PORT: 3000
    volumes:
      - ../apps/web:/app:cached
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"